### ISSUE TITLE
UMD and IIFE not supported error on build with 3.1.0

### ISSUE THREAD

**Issue by martinspriggs** [ItalyPaleAle/svelte-spa-router#174]
When using "asyncComponent: () => import("./Admin.svelte")" inside wrap and then trying to build, getting the follow error:
[!] Error: UMD and IIFE output formats are not supported for code-splitting builds.
Error: UMD and IIFE output formats are not supported for code-splitting builds.
    at error (/Users/martinspriggs/Dev/ContactUs/node_modules/rollup/dist/shared/rollup.js:5265:30)
    at validateOptionsForMultiChunkOutput (/Users/martinspriggs/Dev/ContactUs/node_modules/rollup/dist/shared/rollup.js:12526:16)
    at Bundle$1.generate (/Users/martinspriggs/Dev/ContactUs/node_modules/rollup/dist/shared/rollup.js:12376:17)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at handleGenerateWrite (/Users/martinspriggs/Dev/ContactUs/node_modules/rollup/dist/shared/rollup.js:19992:23)
    at async Promise.all (index 0)
    at build (/Users/martinspriggs/Dev/ContactUs/node_modules/rollup/dist/bin/rollup:1494:5)
    at runRollup (/Users/martinspriggs/Dev/ContactUs/node_modules/rollup/dist/bin/rollup:1645:21)

When replacing "asyncComponent: () => import("./Admin.svelte")" with "condition: Admin" it builds successfully. npm run dev works fine.

**Comment by ItalyPaleAle** [comment]
The error isn't with the router but rather with the fact that Rollup doesn't let you use code splitting (required for dynamic imports) when you set output mode to UMD or IIFE.

Set the output format to `esm`, as in the example: https://github.com/ItalyPaleAle/svelte-spa-router/tree/master/examples/dynamic-imports
